Vendas_SaintLuiger/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vendas_SaintLuiger.Models
{
    [Table("Categorias")]

    public class Categoria
    {
        [Key]
        public int CategoriaId { get; set; }

        [StringLength(100,ErrorMessage ="Tamanho maximo é de 100 caracteres.")]
        [Required(ErrorMessage ="Informe o nome da categoria.")]
        [Display(Name ="Nome")]
        public string CategoriaNome { get; set; }

        [StringLength(200, ErrorMessage = "Tamanho maximo é de 100 caracteres.")]
        [Required(ErrorMessage = "Informe o descrição da categoria.")]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        public List<Sorvete> Sorvetes { get; set; }

    }
}

Vendas_SaintLuiger/Models/ErrorViewModel.cs
namespace Vendas_SaintLuiger.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
       
    }
}

Vendas_SaintLuiger/Models/Sorvete.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Vendas_SaintLuiger.Models
{
    [Table("Sorvetes")]
    public class Sorvete
    {
        [Key]
        public int SorveteId { get; set; }

        [Required(ErrorMessage = "Informe do sorvete deve ser informado.")]
        [Display(Name = "Nome do Sorvete")]
        [StringLength(80, MinimumLength = 10, ErrorMessage ="O {0} deve ter no minímo {1} e no máximo {2}")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "A descrição do sorvete deve ser informado.")]
        [Display(Name = "Descrição do Sorvete")]
        [MinLength(20,ErrorMessage = "A descrição deve ter no minímo {0} caracteres.")]
        [MaxLength(200,ErrorMessage = "A descrição deve ter no máximo {0} caracteres")]
        public string DescricaoCurta { get; set; }

        [Required(ErrorMessage = "A descrição detalhada do sorvete deve ser informado.")]
        [Display(Name = "Descrição detalhada do Sorvete")]
        [MinLength(20, ErrorMessage = "A descrição deve ter no minímo {0} caracteres.")]
        [MaxLength(200, ErrorMessage = "A descrição deve ter no máximo {0} caracteres")]
        public string DescricaoDetalhada { get; set; }
        
        [Required(ErrorMessage = "Informe o preço do Sorvete")]
        [Display(Name ="Preço")]
        [Column(TypeName = "decimal(10,2)")]
        [Range(1,999.99,ErrorMessage ="O preço deve estar entre 1 e 999.99")]
        public decimal Preco{ get; set; }
        [Display(Name = "Caminho imagem Normal")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1}")]
        public string ImagemUrl { get; set; }
        [Display(Name = "Caminho imagem miniatura")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1}")]
        public string ImagemThumbnailUrl { get; set; }
        [Display(Name = "Preferido?")]
        public bool IsSorvetePreferido { get; set; }

        [Display(Name = "Estoque")]
        public bool EmEstoque { get; set; }
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }

        
    }
}

Vendas_SaintLuiger/ViewModels/SorveteListViewModel.cs
using Vendas_SaintLuiger.Models;

namespace Vendas_SaintLuiger.ViewModels
{
    public class SorveteListViewModel
    {
        public IEnumerable<Sorvete> Sorvetes { get; set; }
        public string CategoriaAtual { get; set; }

    }
}

Vendas_SaintLuiger/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vendas_SaintLuiger.Models;

namespace Vendas_SaintLuiger.Controllers
{
    public class HomeController : Controller
    {
      

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vendas_SaintLuiger/Controllers/SorveteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Vendas_SaintLuiger.Models;
using Vendas_SaintLuiger.Repositories.Interfaces;
using Vendas_SaintLuiger.ViewModels;


namespace Vendas_SaintLuiger.Controllers
{
    public class SorveteController : Controller
    {

        private readonly ISorveteRepository _sorveteRepository;

        public SorveteController(ISorveteRepository sorveteRepository)
        {
            _sorveteRepository = sorveteRepository;
        }

        public IActionResult List(string categoria)
        {

            IEnumerable<Sorvete> Sorvetes;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                Sorvetes = _sorveteRepository.Sorvetes.OrderBy(l => l.SorveteId);
                categoriaAtual = "Todos os Sorvetes";
            }
            else
            {
                if (string.Equals("Picole Tradicional", categoria, StringComparison.OrdinalIgnoreCase))
                {
                        Sorvetes = _sorveteRepository.Sorvetes
                        .Where(l => l.Categoria.CategoriaNome.Equals("Picole Tradicional"))
                        .OrderBy(l => l.SorveteId);
                }
                else
                {
                    Sorvetes = _sorveteRepository.Sorvetes
                   .Where(l => l.Categoria.CategoriaNome.Equals("Picole Premium"))
                   .OrderBy(l => l.SorveteId);
                }


                categoriaAtual = categoria;
            }

            ViewData["Title"] = "Sorvetes |";

            var SorveteListViewModel = new SorveteListViewModel
            {
                Sorvetes = Sorvetes,
                CategoriaAtual = categoriaAtual
            };

            return View(SorveteListViewModel);
        }
    }
}

Vendas_SaintLuiger/Views/Home/Index.cshtml
<link rel="stylesheet" href="/css/index.css"/>

<partial name="_Carousel"/>
<br>
<h4 class="titulohistoria">Um pouco de nossa hístoria</h4>
<br>


<figure class="figure rounded float-end">
  <img src="~/images/Saint.png" class="rounded float-end imghistoria img-fluid" alt="...">
  <figcaption class="figure-caption text-center">R. josé menino, n°305, PQ. Rincão Cotia/SP.</figcaption>
</figure>
<p class="historia">
Fundada em setembro de 1995, consegue suas primeiras vendas em outubro do mesmo ano.
Nasceu fruto da amizade e do espírito empreendedor de seus fundadores.<br>

Nos primeiros 5 anos de operação, se dedica, exclusivamente, à industrialização e comercio de sorvetes.
No inicio do século XXI se inicia a venda, no atacado, de outros produtos alimentícios. <br>

Temos hoje parcerias com mais de 6.000 pontos de revenda espalhados principalmente pela cidade de São Paulo e 
interior do estado. Isto nunca teria sido possível sem a confiança de nossos clientes e consumidores.<br>

Com o trabalho e a determinação de todos aqueles que integram esta grande equipe chamada “Saint Luiger”, 
temos certeza que ainda conquistaremos a preferência de muitos consumidores e colocaremos alimentos e bebidas na 
mesa de muitas famílias brasileiras.<br>
</p><br></br>

<form style="border:solid black 1px; padding:10px;">
  <fieldset enable>
    <legend>Contato/Atendimento</legend>
    <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Nome</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Nome Completo">
    </div>
    <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Endereço</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Rua/Bairro/Cidade">
    </div>
    <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Cep</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="000000-000">
    </div>
     <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Telefone</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="(00) 00000-0000">
    </div>
     <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Email</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="amosorvetes@gmail.com">
    </div>
     <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Assunto</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Quero Saint Luiger no meu negócio!">
    </div>
    <div class="mb-3">
      <label for="disabledTextInput" class="form-label">Mensagem</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Quero revender sorvetes!!!">
    </div>

    <div class="mb-3">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="disabledFieldsetCheck" enable>
        <label class="form-check-label" for="disabledFieldsetCheck">
          Quero receber novidades!
        </label>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </fieldset>
</form>

Vendas_SaintLuiger/Views/Shared/_Carousel.cshtml
<div id="carouselSorvetes" class="carousel slide img-fluid" style="position:relative; width:100%; height: 100%;">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/images/1.jpg" class="w-100 img-fluid" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/images/2.jpg" class="w-100 img-fluid" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/images/3.jpg" class="w-100 img-fluid" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselSorvetes" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselSorvetes" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Vendas_SaintLuiger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  SaintLuiger</title>
    <link rel="icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vendas_SaintLuiger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow align-self-baseline">
            <div class="container-fluid">
                <a class="navbar-brand" style="font-size:22pt; font-style:oblique" asp-area="" asp-controller="Home" asp-action="Index">SaintLuiger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="font-size:16pt">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn-lg dropdown-toggle" type="button" style="border:none;background-color:white; font-size:16pt" id="dropdownSorvetes" data-bs-toggle="dropdown" aria-expanded="false">
                                    Sorvetes
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownSorvetes">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Sorvete" asp-action="List" style="color: black"
                                           asp-route-categoria="Picole Tradicional">Picole Tradicional</a>
                                           <a class="dropdown-item" asp-controller="Sorvete" asp-action="List" style="color: black"
                                           asp-route-categoria="Picole Premium">Picole Premium</a>
                                    </li>
                                    <hr>
                                    <li> <a class="dropdown-item" asp-controller="Sorvete" asp-action="List" asp-route-categoria=""  style="color:black">
                                        Todos os sorvetes</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Outros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Receitas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Curiosidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - Vendas_SaintLuiger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vendas_SaintLuiger/Views/Sorvete/List.cshtml
@model SorveteListViewModel

<br>
<h1>@Model.CategoriaAtual</h1>
</br>
<br>
<tbody>

    <div class="container">
        <div class="row">
            @foreach (var item in Model.Sorvetes)
            {
                <div class="col-sm-4 col-md-4 col-lg-4">
                    <p><img src="@item.ImagemUrl" style="width:280px; height: 280px;" class="img-fluid"></p>
                    <h5>Nome: @item.Nome </h5>
                    <h6>@item.DescricaoCurta</h6>
                    <h7>Preço Sugerido: R$@item.Preco</h7>
                    <p>
                </div>

            }
        </div>
    </div>
</tbody>
</table>